apiVersion: v1
kind: Service
metadata:
  name: nginix
  labels:
    app: nginix
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginix
  type: LoadBalancer
